# Generated by Django 4.2.7 on 2025-10-28 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalInvestigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organization', models.CharField(help_text='Company/University/Institute name', max_length=255)),
                ('department', models.CharField(blank=True, help_text='Department within the organization', max_length=255)),
                ('country', models.CharField(blank=True, help_text='Country of affiliation', max_length=100)),
                ('designation', models.CharField(blank=True, help_text='Position/Title (e.g., Professor, Research Scientist)', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional information about the investigator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalAlternateID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Identifier type (e.g., 'old_system_id', 'funding_ref')", max_length=100)),
                ('value', models.CharField(help_text='The alternate identifier value', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this alternate ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='proposalinvestigator',
            name='unique_proposal_investigator',
        ),
        migrations.AddField(
            model_name='fundingagency',
            name='code',
            field=models.CharField(default='NAN', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='historicalproposal',
            name='date_approved',
            field=models.DateTimeField(blank=True, help_text='Date when status changed to APPROVED', null=True),
        ),
        migrations.AddField(
            model_name='historicalproposal',
            name='date_closed',
            field=models.DateTimeField(blank=True, help_text='Date when status changed to CLOSED', null=True),
        ),
        migrations.AddField(
            model_name='historicalproposal',
            name='date_disbursed',
            field=models.DateTimeField(blank=True, help_text='Date when status changed to DISBURSED', null=True),
        ),
        migrations.AddField(
            model_name='historicalproposal',
            name='date_draft',
            field=models.DateTimeField(blank=True, editable=False, help_text='Date proposal was created/drafted', null=True),
        ),
        migrations.AddField(
            model_name='historicalproposal',
            name='date_on_hold',
            field=models.DateTimeField(blank=True, help_text='Date when status changed to ON_HOLD', null=True),
        ),
        migrations.AddField(
            model_name='historicalproposal',
            name='date_permission',
            field=models.DateTimeField(blank=True, help_text='Date when status changed to PERMISSION', null=True),
        ),
        migrations.AddField(
            model_name='historicalproposal',
            name='date_rejected',
            field=models.DateTimeField(blank=True, help_text='Date when status changed to REJECTED', null=True),
        ),
        migrations.AddField(
            model_name='historicalproposal',
            name='date_review',
            field=models.DateTimeField(blank=True, help_text='Date when status changed to REVIEW', null=True),
        ),
        migrations.AddField(
            model_name='historicalproposal',
            name='date_submitted',
            field=models.DateTimeField(blank=True, help_text='Date when status changed to SUBMITTED', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='date_approved',
            field=models.DateTimeField(blank=True, help_text='Date when status changed to APPROVED', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='date_closed',
            field=models.DateTimeField(blank=True, help_text='Date when status changed to CLOSED', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='date_disbursed',
            field=models.DateTimeField(blank=True, help_text='Date when status changed to DISBURSED', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='date_draft',
            field=models.DateTimeField(auto_now_add=True, help_text='Date proposal was created/drafted', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='date_on_hold',
            field=models.DateTimeField(blank=True, help_text='Date when status changed to ON_HOLD', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='date_permission',
            field=models.DateTimeField(blank=True, help_text='Date when status changed to PERMISSION', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='date_rejected',
            field=models.DateTimeField(blank=True, help_text='Date when status changed to REJECTED', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='date_review',
            field=models.DateTimeField(blank=True, help_text='Date when status changed to REVIEW', null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='date_submitted',
            field=models.DateTimeField(blank=True, help_text='Date when status changed to SUBMITTED', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='funding_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='proposals.fundingagency'),
        ),
        migrations.AlterField(
            model_name='proposalinvestigator',
            name='investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal_involvements', to='proposals.investigator'),
        ),
        migrations.AddField(
            model_name='proposalinvestigator',
            name='external_investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal_involvements', to='proposals.externalinvestigator'),
        ),
        migrations.AddField(
            model_name='proposalalternateid',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_ids', to='proposals.proposal'),
        ),
        migrations.AddConstraint(
            model_name='proposalinvestigator',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('external_investigator__isnull', True), ('investigator__isnull', False)), models.Q(('external_investigator__isnull', False), ('investigator__isnull', True)), _connector='OR'), name='either_internal_or_external_investigator'),
        ),
        migrations.AddConstraint(
            model_name='proposalinvestigator',
            constraint=models.UniqueConstraint(condition=models.Q(('investigator__isnull', False)), fields=('proposal', 'investigator'), name='unique_internal_investigator_per_proposal'),
        ),
        migrations.AddConstraint(
            model_name='proposalinvestigator',
            constraint=models.UniqueConstraint(condition=models.Q(('external_investigator__isnull', False)), fields=('proposal', 'external_investigator'), name='unique_external_investigator_per_proposal'),
        ),
        migrations.AddIndex(
            model_name='proposalalternateid',
            index=models.Index(fields=['key', 'value'], name='proposals_p_key_bccd92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proposalalternateid',
            unique_together={('proposal', 'key')},
        ),
    ]
