# Generated by Django 4.2.7 on 2025-10-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_externalinvestigator_proposalalternateid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalinvestigator',
            name='code',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate (format: EXXXX). Or enter a custom code.', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalproposal',
            name='gcir_code',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='gcir_code',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
