# Generated by Django 4.2.7 on 2025-10-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_alter_externalinvestigator_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalinvestigator',
            name='code',
            field=models.CharField(blank=True, help_text='Leave blank to auto-generate (format: EXXXX). Or enter a custom code.', max_length=32, null=True, unique=True),
        ),
    ]
