# Generated by Django 4.2.7 on 2025-10-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_alter_externalinvestigator_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproposal',
            name='date_draft',
            field=models.DateTimeField(blank=True, help_text='Date proposal was created/drafted', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_draft',
            field=models.DateTimeField(blank=True, help_text='Date proposal was created/drafted', null=True),
        ),
    ]
