# Generated by Django 4.2.7 on 2025-10-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_alter_historicalproposal_date_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproposal',
            name='date_approved',
            field=models.DateField(blank=True, help_text='Date when status changed to APPROVED', null=True),
        ),
        migrations.AlterField(
            model_name='historicalproposal',
            name='date_closed',
            field=models.DateField(blank=True, help_text='Date when status changed to CLOSED', null=True),
        ),
        migrations.AlterField(
            model_name='historicalproposal',
            name='date_disbursed',
            field=models.DateField(blank=True, help_text='Date when status changed to DISBURSED', null=True),
        ),
        migrations.AlterField(
            model_name='historicalproposal',
            name='date_draft',
            field=models.DateField(blank=True, help_text='Date proposal was created/drafted', null=True),
        ),
        migrations.AlterField(
            model_name='historicalproposal',
            name='date_on_hold',
            field=models.DateField(blank=True, help_text='Date when status changed to ON_HOLD', null=True),
        ),
        migrations.AlterField(
            model_name='historicalproposal',
            name='date_permission',
            field=models.DateField(blank=True, help_text='Date when status changed to PERMISSION', null=True),
        ),
        migrations.AlterField(
            model_name='historicalproposal',
            name='date_rejected',
            field=models.DateField(blank=True, help_text='Date when status changed to REJECTED', null=True),
        ),
        migrations.AlterField(
            model_name='historicalproposal',
            name='date_review',
            field=models.DateField(blank=True, help_text='Date when status changed to REVIEW', null=True),
        ),
        migrations.AlterField(
            model_name='historicalproposal',
            name='date_submitted',
            field=models.DateField(blank=True, help_text='Date when status changed to SUBMITTED', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_approved',
            field=models.DateField(blank=True, help_text='Date when status changed to APPROVED', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_closed',
            field=models.DateField(blank=True, help_text='Date when status changed to CLOSED', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_disbursed',
            field=models.DateField(blank=True, help_text='Date when status changed to DISBURSED', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_draft',
            field=models.DateField(blank=True, help_text='Date proposal was created/drafted', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_on_hold',
            field=models.DateField(blank=True, help_text='Date when status changed to ON_HOLD', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_permission',
            field=models.DateField(blank=True, help_text='Date when status changed to PERMISSION', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_rejected',
            field=models.DateField(blank=True, help_text='Date when status changed to REJECTED', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_review',
            field=models.DateField(blank=True, help_text='Date when status changed to REVIEW', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='date_submitted',
            field=models.DateField(blank=True, help_text='Date when status changed to SUBMITTED', null=True),
        ),
    ]
